---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 80, host: 8080}]
    - ["forwarded_port", {guest: 8081, host: 8081}]

provisioner:
  name: chef_zero
  data_bags_path: "test/integration/data_bags"
  roles_path: "test/integration/roles"

platforms:
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - role[class]
      - recipe[chef_portal::fundamentals_3x]
    attributes:
      ec2:
        iam:
          security-credentials:
            provisioner:
              AccessKeyId: 'ACCESS KEY'
              SecretAccessKey: 'SECRET ACCESS KEY'
